-- MySQL Script generated by MySQL Workbench
-- wo 19 jul 2017 22:26:33 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Framework
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Framework
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Framework` DEFAULT CHARACTER SET utf8 ;
USE `Framework` ;

-- -----------------------------------------------------
-- Table `Framework`.`Personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Framework`.`Personal` ;

CREATE TABLE IF NOT EXISTS `Framework`.`Personal` (
  `idPersonal` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idPersonal`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Framework`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Framework`.`Users` ;

CREATE TABLE IF NOT EXISTS `Framework`.`Users` (
  `idUsers` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `idPersonal` INT(11) NOT NULL,
  PRIMARY KEY (`idUsers`),
  INDEX `idPersonal` (`idPersonal` ASC),
  CONSTRAINT `PersonalTable`
    FOREIGN KEY (`idPersonal`)
    REFERENCES `Framework`.`Personal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Framework`.`Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Framework`.`Log` ;

CREATE TABLE IF NOT EXISTS `Framework`.`Log` (
  `idLog` INT(11) NOT NULL AUTO_INCREMENT,
  `idUser` INT(11) NOT NULL,
  `Logtext` VARCHAR(255) NOT NULL,
  `LogDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idLog`),
  INDEX `idUser` (`idUser` ASC),
  CONSTRAINT `User`
    FOREIGN KEY (`idUser`)
    REFERENCES `Framework`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Framework`.`Perm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Framework`.`Perm` ;

CREATE TABLE IF NOT EXISTS `Framework`.`Perm` (
  `idPerm` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idPerm`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Framework`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Framework`.`Role` ;

CREATE TABLE IF NOT EXISTS `Framework`.`Role` (
  `idRole` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Framework`.`Visitors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Framework`.`Visitors` ;

CREATE TABLE IF NOT EXISTS `Framework`.`Visitors` (
  `idVisitors` INT(11) NOT NULL AUTO_INCREMENT,
  `Uniek` TINYINT(1) NOT NULL DEFAULT '0',
  `Page` VARCHAR(255) NOT NULL,
  `IP` VARCHAR(255) NOT NULL,
  `VisitDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idVisitors`))
ENGINE = InnoDB
AUTO_INCREMENT = 73
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Framework`.`Vistors_online`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Framework`.`Vistors_online` ;

CREATE TABLE IF NOT EXISTS `Framework`.`Vistors_online` (
  `idVistors_online` INT(11) NOT NULL AUTO_INCREMENT,
  `IP` VARCHAR(255) NOT NULL,
  `Last_seen` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idVistors_online`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Framework`.`permRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Framework`.`permRole` ;

CREATE TABLE IF NOT EXISTS `Framework`.`permRole` (
  `idpermRole` INT(11) NOT NULL AUTO_INCREMENT,
  `idRole` INT(11) NOT NULL,
  `idPerm` INT(11) NOT NULL,
  PRIMARY KEY (`idpermRole`),
  INDEX `Role` (`idRole` ASC),
  INDEX `Permission` (`idPerm` ASC),
  CONSTRAINT `Permissions`
    FOREIGN KEY (`idPerm`)
    REFERENCES `Framework`.`Perm` (`idPerm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Role`
    FOREIGN KEY (`idRole`)
    REFERENCES `Framework`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Framework`.`userRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Framework`.`userRole` ;

CREATE TABLE IF NOT EXISTS `Framework`.`userRole` (
  `iduserRole` INT(11) NOT NULL AUTO_INCREMENT,
  `idUser` INT(11) NOT NULL,
  `idRole` INT(11) NOT NULL,
  PRIMARY KEY (`iduserRole`),
  INDEX `User` (`idUser` ASC),
  INDEX `Role` (`idRole` ASC),
  CONSTRAINT `rollen`
    FOREIGN KEY (`idRole`)
    REFERENCES `Framework`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `users`
    FOREIGN KEY (`idUser`)
    REFERENCES `Framework`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Framework`.`Perm`
-- -----------------------------------------------------
START TRANSACTION;
USE `Framework`;
INSERT INTO `Framework`.`Perm` (`idPerm`, `description`) VALUES (DEFAULT, 'adminpanel');
INSERT INTO `Framework`.`Perm` (`idPerm`, `description`) VALUES (DEFAULT, 'checkuser');
INSERT INTO `Framework`.`Perm` (`idPerm`, `description`) VALUES (DEFAULT, 'updateuser');
INSERT INTO `Framework`.`Perm` (`idPerm`, `description`) VALUES (DEFAULT, 'createuser');
INSERT INTO `Framework`.`Perm` (`idPerm`, `description`) VALUES (DEFAULT, 'changerole');
INSERT INTO `Framework`.`Perm` (`idPerm`, `description`) VALUES (DEFAULT, 'changeUserRole');
INSERT INTO `Framework`.`Perm` (`idPerm`, `description`) VALUES (DEFAULT, 'createRole');
INSERT INTO `Framework`.`Perm` (`idPerm`, `description`) VALUES (DEFAULT, 'Role');
INSERT INTO `Framework`.`Perm` (`idPerm`, `description`) VALUES (DEFAULT, 'Tables');
INSERT INTO `Framework`.`Perm` (`idPerm`, `description`) VALUES (DEFAULT, 'ChangeTable');
INSERT INTO `Framework`.`Perm` (`idPerm`, `description`) VALUES (DEFAULT, 'Log');
INSERT INTO `Framework`.`Perm` (`idPerm`, `description`) VALUES (DEFAULT, 'statistics');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Framework`.`Role`
-- -----------------------------------------------------
START TRANSACTION;
USE `Framework`;
INSERT INTO `Framework`.`Role` (`idRole`, `name`) VALUES (DEFAULT, 'admin');
INSERT INTO `Framework`.`Role` (`idRole`, `name`) VALUES (DEFAULT, 'Default');
INSERT INTO `Framework`.`Role` (`idRole`, `name`) VALUES (DEFAULT, 'moderator');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Framework`.`permRole`
-- -----------------------------------------------------
START TRANSACTION;
USE `Framework`;
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 6, 14);
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 6, 15);
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 6, 16);
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 6, 17);
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 6, 18);
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 6, 19);
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 6, 20);
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 6, 21);
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 6, 22);
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 6, 23);
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 6, 24);
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 6, 25);
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 3, 15);
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 3, 17);
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 3, 14);
INSERT INTO `Framework`.`permRole` (`idpermRole`, `idRole`, `idPerm`) VALUES (DEFAULT, 3, 16);

COMMIT;

